### ISSUE TITLE
[WooCommerce] Order data not incorporated

### ISSUE THREAD

**Issue by michaelhartl** [deliciousbrains/wp-migrate-db-anonymization#11]
The order data is not incorporated in the anonymization process. In the orders list in backend and in the order details you have the original data.

As far as I can see, the orders are stored in "wp_postmeta". The following data set entries are relevant:

value of meta_key // info, if necessary

- _billing_address_index // complete billing address with frist-&lastname, street, city, countrycode, email-adress and telephone-number
- _shipping_address_index // complete shipping address with frist-&lastname, street, city and countrycode
- _billing_fax // fax number
- _shipping_fax // fax number
- _shipping_country // country code
- _billing_first_name
- _billing_last_name
- _billing_company
- _billing_address_1
- _billing_address_2
- _billing_city
- _billing_state
- _billing_postcode
- _billing_country // country code
- _billing_email
- _billing_phone
- _shipping_first_name
- _shipping_last_name
- _shipping_company
- _shipping_address_1
- _shipping_address_2
- _shipping_city
- _shipping_state
- _shipping_country // country code
- _shipping_postcode
- _customer_ip_address
- Payer PayPal address // email address
- Payer first name
- Payer last name

**Comment by michaelhartl** [comment]
just edited it ..... sometimes I realize things shortly after hitting Comment or Send. ;)

**Comment by polevaultweb** [comment]
Thanks @michaelhartl, I'll get that added to the Woo config shortly. Or if you get chance, feel free to PR 👍

**Comment by polevaultweb** [comment]
Fixed by https://github.com/deliciousbrains/wp-migrate-db-anonymization/commit/5508a6c782b9efc8118562b5606b64bc3cec7d50
