### ISSUE TITLE
[Question about project strategy] How to extend this plugin

### ISSUE THREAD

**Issue by ibes** [deliciousbrains/wp-migrate-db-anonymization#13]
Hello,

we want to use this plugin in combination with WP Migrate DB Pro to combine comfort and data security for our projects. 

We need more than just the users table to be anonymized. 
So the question is: How to extend the project. 

You already offer a way to extend the data that need to be anonymized but we want to use this for all our projects and, as we believe in data protection, we want others to have a easy time with it. 

Ways I see:
- extend the plugin with the basics (eg comments) + the classics (eg. woocommerce)
- have small plugins to extend this plugin - link "wp-migrate-db-anonymization for WooCommerce" - that could clutter our plugin repo a bit too much 
- we could offer an extension plugin that collects everything we need and offers others to provide merge requests. Then maybe give an option to check with anonymization you want to have. That is something we can do anyway - with or without your support. 

My favorite would be to have an official collection of anonymization setups. 
Maybe you want to set this up as an additional repo or in the wiki. 
Maybe we can start this and see where it leads. 
So there could be config snippets for comments, woocommerce etc. 
Easy for developers to collect what they need and tweak where needed - but not easy for end users. 
But a) we are developers and b) things could be ready enough to throw them into a functions.php or into https://de.wordpress.org/plugins/code-snippets/

Is there already a strategy?
Are you up for an official configuration collection?
Should we do that?
@michaelhartl and I are up for make our progress usable for others.

**Comment by polevaultweb** [comment]
@ibes so @michaelhartl has already raised a PR for the comments. I think the bets approach is to extend for your own use and submit PR's here so this plugin keeps it all together. Obviously any data bespoke to your project should be kept as separate extensions.

**Comment by ibes** [comment]
Great - so that is the way we will do it :)
