### ISSUE TITLE
`wpmdb_anonymization_user_whitelisted` not being reached

### ISSUE THREAD

**Issue by jongc** [deliciousbrains/wp-migrate-db-anonymization#15]
The example you have in the README docs is missing the closing quote after `@somedomain.com`.

But the real issue I'm having is the filter `wpmdb_anonymization_user_whitelisted`. It's not working for me. This is what I have firing from the theme's function.php:

```php
add_filter( 'wpmdb_anonymization_user_whitelisted', function ( $whitelisted, $user_login ) {
	// Test when filter is fired
	error_log( $user_login );

	// Bypass and whitelist all users with organization domain
	if ( false !== strpos( $user_login, 'mydomain.com' ) ) {
		return true;
	}

	// If reached here, return boolean $whitelisted untouched
	return $whitelisted;
}, 10, 2 );
```

I tried debugging the filter using my example above by throwing in an `error_log()` to see if the filter gets hit. The `error_log()` never fires. I also changed all return statements to return `true` so all users are whitelisted. That doesn't work either–all user data are still being replaced with fake data.

**Comment by polevaultweb** [comment]
@jongc thanks for the heads up on the typo.

This won't fire from the theme's functions.php at the theme doesn't get loaded in the WP admin. I've updated the readme to suggest using a plugin or mu-plugin.

**Comment by jongc** [comment]
Thanks for the info. I will test through a plugin.
