### ISSUE TITLE
Question for extending $config for non-prefixed WordPress tables

### ISSUE THREAD

**Issue by jongc** [deliciousbrains/wp-migrate-db-anonymization#16]
This is my understanding of the configurations in the README docs.

```php
function my_wpmdb_anonymization_rules( $config ) {
	$config['usermeta']['meta_value'][] = array(
		'constraint' => array( 'meta_key' => 'dob' ),
		'fake_data_type' => 'dateTimeThisCentury',
	);

	return $config;
}
```

... where `usermeta` is for the table `wp_usermeta` and `meta_value` is for the column `meta_value` in `wp_usermeta`. What if the table doesn't have a prefix like `my_table` instead of `wp_my_table`? Would it take the following configuration regardless of the prefix?

```php
function my_wpmdb_anonymization_rules( $config ) {
	$config['my_table']['my_table_column'][] = array(
		'constraint' => array( 'my_table_key' => 'dob' ),
		'fake_data_type' => 'dateTimeThisCentury',
	);

	return $config;
}
```

**Comment by polevaultweb** [comment]
@jongc that should work fine, as the prefix is removed from the table before the anonymization rules are run, so if the table doesn't have it in the first place it won't be removed 👍

**Comment by jongc** [comment]
Thanks for the info. I'm assuming this configuration should also happen through a plugin as you mentioned for the other filter issue that I submitted in https://github.com/deliciousbrains/wp-migrate-db-anonymization/issues/15.

**Comment by polevaultweb** [comment]
@jongc correct - i've just made that clearer in the README
