### ISSUE TITLE
Passing function parameter through $config

### ISSUE THREAD

**Issue by jongc** [deliciousbrains/wp-migrate-db-anonymization#18]
I'm extending `$config` to anonymize data for non-WordPress tables. Is there a way to pass parameters to the callable function that gets assigned to `fake_data_type`? For example, I want to do something like this:

```
$config['custom_table'][] = [
	'date_column' => [
		// Specify a different date format for fake data
		'fake_data_type' => "date('m/d/Y')",
	]
];
```

**Comment by polevaultweb** [comment]
@jongc Support for this is added in version 0.3:

```
'fake_data_type' => 'date',
'fake_data_args' => array( 'Y-m-d' ),
```
