### ISSUE TITLE
Whitelisting user email addresses does not work

### ISSUE THREAD

**Issue by indrek-k** [deliciousbrains/wp-migrate-db-anonymization#21]
Hi there!

Whitelisting users by their email address doesn't appear to work (even though it's specifically mentioned in the readme). I've tested the following options:

1) in wp-config
`define('WPMDB_ANONYMIZATION_USER_LOGIN_WHITELIST', 'example@codelight.eu');`

2) in a separate plugin
```
add_filter('wpmdb_anonymization_user_whitelisted', function($whitelisted, $user_login) {
    if (false !== strpos($user_login, '@codelight.eu')) {
        return true;
    }
    
    return $whitelisted;
}, 10, 2);
```
However, when I tested the same thing with the actual username instead of email, everything worked nicely.

Looking at the source of the plugin, I'm getting the feeling that using an email there couldn't work anyway:
```
public static function is_not_whitelisted_user( $row ) {
	if ( ! isset( $row->user_login ) ) {
		return true;
	}

	return ! self::is_whitelisted_user( $row->user_login );
}
```
Please advise. Thanks!

**Comment by polevaultweb** [comment]
Thanks for this, yep looks like a bug as our site that I tested it on uses the emails as the user_login.

**Comment by indrek-k** [comment]
Do you think you could just pass the $row variable into the filter? This way it would be possible to use either the email or the username.

**Comment by indrek-k** [comment]
Awesome, thank you!
