### ISSUE TITLE
Deprecated class WPMDB_Base in wp-migrate-db plugin

### ISSUE THREAD

**Issue by lex127** [deliciousbrains/wp-migrate-db-anonymization#23]
Hello! 
In wp-migrate-db-anonymization uses WPMDB_Base class from wp-migrate-db plugin but in version 1.0.6 this class was deprecated and it does not exist.
Which means the plugin does not support the latest version...

**Comment by polevaultweb** [comment]
This is fixed in https://github.com/deliciousbrains/wp-migrate-db-anonymization/commit/941a2156cd81b603222a8d2af016ad02eaf5f946 but you will need to update to 1.0.7 of WP Migrate DB, hopefully released later today.

**Comment by polevaultweb** [comment]
🎉 0.3.3 released https://wordpress.org/plugins/wp-migrate-db-anonymization/
