### ISSUE TITLE
Faker should respect site's locale

### ISSUE THREAD

**Issue by tyrann0us** [deliciousbrains/wp-migrate-db-anonymization#25]
>`Faker\Factory` can take a locale as an argument, to return localized data. If no localized provider is found, the factory fallbacks to the default locale (en_US).
>
> &mdash; <cite>[Localization](https://github.com/fzaninotto/Faker/#localization)</cite>

So for example, to create a German faker instance, pass `de_DE` to the factory:
```
$faker = Factory::create( 'de_DE' );
```

Since this is very easy (and safe) to implement, the plugin should respect the site's locale. For this to work you only need to change line
https://github.com/deliciousbrains/wp-migrate-db-anonymization/blob/cca4ad85ca9d73b5bb2ae76347a0b6d3f3c5913d/includes/Plugin.php#L82
to
```
$faker = Factory::create( get_locale() );
```

See [`get_locale()`](https://developer.wordpress.org/reference/functions/get_locale/).

**Comment by tyrann0us** [comment]
I've been thinking about it.
Respecting a site's locale is a good idea for "normal" sites. In a [Multisite](https://wordpress.org/support/article/glossary/#multisite), however, the migration runs in the network area, which means that for _multilingual Multisites_ `Faker` is still initialized only in one locale (the main site's locale). This is no real improvement compared to the current situation.

It might be challenging or impossible with the current code architecture to check if different languages are set and to initialize `Faker` for each site individually.

@polevaultweb, what do you think?

**Comment by polevaultweb** [comment]
@tyrann0us it's probably not worth it to do anything differently for Multisite. Using the site's locale is a good improvement, but at the end of the day fake data is fake data whatever the language of the site.
